---
title: "Data Simulation"
author: "Lucas Leiter"
date: "3/8/2021"
output: html_document
---

```{r setup, include=FALSE}
library(dplyr)
library(caret)
```

We estimate a statistical model to predict the superconducting critical temperature based on the superconductor's chemical formula



```{r}
train<-read.csv("train.csv")

head(train)

#critical_temp --> is the y we are trying to calculate
```

#calculate the true betas

```{r}
set.seed(45)
ols_model<-train(
  critical_temp~.,
  data=train, 
  method="lm",
  trControl = trainControl(method = "cv", number = 10)
)
summary(ols_model)
```


```{r}
betas<-coef(ols_model$finalModel)
length(betas)

betas<-betas[2:82]
```



```{r}
x<- data.matrix(train[,1:81])
```


```{r}
e<- rnorm(nrow(train), 0, 17.59) 
```


```{r}
y<-x%*%betas + e
```


```{r}
df<-data.frame(y,x)

head(df)
```


```{r}
params<- preProcess(df, method = c("center","scale"))

transformed<- predict(params, df)

transformed
```



# OLS
```{r}
set.seed(45)
ols_model<-train(
  y~.,
  data=transformed, 
  method="lm",
  trControl = trainControl(method = "cv", number = 10)
)
summary(ols_model)

```


```{r}
ols_model$results
```

```{r}
ols_model$resample
```


```{r}
ols_model$resample%>%
  summarize(cv_mae=mean(MAE))
```



# Ridge ONE SE
```{r}
lambda_grid<-10^seq(-4,1,length=300)
# Set the seed
set.seed(253)

# Perform Ridge
ridge_model <- train(
  y~.,
  data = transformed,
  method = "glmnet",
  trControl = trainControl(method = "cv", number = 10, selectionFunction = "oneSE"),
  tuneGrid = data.frame(alpha = 0, lambda = lambda_grid),
  metric = "MAE",
  na.action = na.omit
)

```


```{r}
# Plot coefficients for each Ridge
plot(ridge_model$finalModel, xvar = "lambda", label = TRUE, col = rainbow(500))
```

```{r}
plot(ridge_model)
```


```{r}
plot(ridge_model, xlim = c(0,0.09), ylim = c(0.43,0.45))
```

```{r}
ridge_model$resample
ridge_model$bestTune

ridge_model$resample%>%
  summarize(cv_mae=mean(MAE))
```



# RIDGE using best
```{r}
lambda_grid<-10^seq(-4,1,length=300)
# Set the seed
set.seed(253)

# Perform Ridge
ridge_model_best <- train(
  y~.,
  data = transformed,
  method = "glmnet",
  trControl = trainControl(method = "cv", number = 10, selectionFunction = "best"),
  tuneGrid = data.frame(alpha = 0, lambda = lambda_grid),
  metric = "MAE",
  na.action = na.omit
)
```


```{r}
# Plot coefficients for each Ridge
plot(ridge_model_best$finalModel, xvar = "lambda", label = TRUE, col = rainbow(500))
```

```{r}
plot(ridge_model_best)
```
```{r}
plot(ridge_model_best, xlim = c(0,0.08), ylim = c(0.40,0.45))
```


```{r}
ridge_model_best$resample
ridge_model_best$resample%>%
  summarize(cv_mae=mean(MAE))
ridge_model_best$bestTune
```


#LASSO
```{r}
lambda_grid<-10^seq(-4,1,length=300)
# Set the seed
set.seed(253)

# Perform Ridge
lasso_model <- train(
  y~.,
  data = transformed,
  method = "glmnet",
  trControl = trainControl(method = "cv", number = 10, selectionFunction = "oneSE"),
  tuneGrid = data.frame(alpha = 1, lambda = lambda_grid),
  metric = "MAE",
  na.action = na.omit
)


```


```{r}
# Plot coefficients for each Lasso
plot(lasso_model$finalModel, xvar = "lambda", label = TRUE, col = rainbow(500))
```

```{r}
plot(lasso_model, xlim=c(0,0.004),ylim=c(0,0.5))
```

```{r}
lasso_model$resample

lasso_model$bestTune
```

```{r}
a<-as.data.frame(as.matrix(coef(lasso_model$finalModel)))

mean_coef<- as.data.frame(rowMeans(a))\

mean_coef
```


# Elastic Net
```{r}

alpha_grid<-10^seq(-3,0,length=50)

lambda_grid<-10^seq(-3,1,length=300)
# Set the seed
set.seed(253)

# Perform Elastic Net
ridge_model <- train(
  y~.,
  data = df,
  method = "glmnet",
  trControl = trainControl(method = "cv", number = 10, selectionFunction = "oneSE"),
  tuneGrid = data.frame(alpha=alpha_grid, lambda = lambda_grid),
  metric = "MAE",
  na.action = na.omit
)


```


```{r}
# Plot coefficients for each Ridge
plot(ridge_model$finalModel, xvar = "lambda", label = TRUE, col = rainbow(500))
```

```{r}
plot(ridge_model, xlim=c(0.1,0.3),ylim=c(0,0.4))
```

```{r}
ridge_model$resample
ridge_model$bestTune
```



#Functions

```{r}
#MSE
get_mse = function(estimate,truth){
  mean((estimate - truth)^2)
}
```

```{r}
#BIAS
get_bias = function(estimate, truth){
  mean(estimate) - truth
}
```

```{r}
#VAR
get_var = function(estimate){
  mean((estimate - mean(estimate))^2)
}
```

```{r}
#bias = apply(predictions, 2, get_bias, truth = y)
#variance = apply(predictions, 2, get_var)
#mse = apply(predictions, 2, get_mse, truth = y)
```




